### ISSUE TITLE
Supporting job dependency/chaining? 

### ISSUE THREAD

**Issue by jbusecke** [kbatch-dev/kbatch#65]
Hey all, 

I am curious if kbatch has the ability to implement job dependencies (e.g. submit job_b only once job_a has finished)? [sbatch does implement this](https://hcc.unl.edu/docs/submitting_jobs/job_dependencies/) and I think this would be a tremendous feature (if not already possible).

**Comment by minrk** [comment]
I think this would definitely be useful. It is a significant increase in scope, though, because it would mean implementing a scheduler inside kbatch-proxy because kubernetes doesn't itself have this concept, as far as I know. kbatch would need the following functionality it doesn't currently have:

1. store jobs (somewhere) to be submitted later (big change because kbatch-proxy is no longer stateless)
2. watch jobs for when they finish (big change because kbatch has an always-running task to take actions when jobs finish)
3. evaluate and submit dependents upon job completion (needs dependency resolver / task DAG logic, introduces concurrency challenges if run with multiple kbatch-proxy replicas)

**Comment by jbusecke** [comment]
Thanks for the explanation here @minrk! This seems indeed like quite the increase in scope. Lets bench this for now.
